import pandas as pd

# 1) Load predictions (from evaluation output)
preds = pd.read_csv("outputs/metrics/test_fusion_preds.csv")

# 2) Load test csv to recover clip_dir in the correct order
test = pd.read_csv("data/splits/test.csv")[["clip_dir", "label"]].reset_index(drop=True)

# sanity check: lengths should match (36)
if len(preds) != len(test):
    raise ValueError(f"Length mismatch: preds={len(preds)} vs test={len(test)}. "
                     "Re-run evaluation with shuffle=False and tta=1.")

# attach clip_dir
preds["clip_dir"] = test["clip_dir"].values

# 3) Load silence report (generated by your silence summary script)
sil = pd.read_csv("outputs/metrics/audio_silence_report.csv")

# Build the same clip_dir format used elsewhere
# Expecting columns: class, clip_id, is_silent, std (or similar)
sil["clip_dir"] = "data/processed/" + sil["class"].astype(str) + "/" + sil["clip_id"].astype(str)

# 4) Merge and display mistakes
m = preds.merge(sil[["clip_dir", "is_silent", "std"]], on="clip_dir", how="left")

mistakes = m[m["y_true"] != m["y_pred"]].copy()
print("Mistakes:", len(mistakes))
print(mistakes[["clip_dir", "y_true", "y_pred", "is_silent", "std"]].to_string(index=False))
